### ISSUE TITLE
Setting your icons

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [KarlofKuwait/Gui-Practice#1]
I saw you're calling SetOption to set the window's icon.  You can also specify it in your call to `Window`.  Use the `icon` parameter in the call:
`Login = sg.Window('RedditBot Login', icon='c:\.......').Layout(layout)`

Not yet documented, but you can specify the layout in the window call too.  It's always the second parameter now, of you can add `layout=` to be more specific..  This would be the most compact form:
`Login = sg.Window('RedditBot Login', layout, icon='c:\.......')`

Glad to see you're playing with it.

**Comment by Archived-Mads** [comment]
Okay, thanks for the heads up, ill try adding it into the code
